[package]
name = "telda2"
version = "0.3.0"
edition = "2021"
default-run = "t"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
collect_result = "0.1"
